# Generated by Django 4.2.4 on 2023-10-19 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_user_watchlist_alter_user_first_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="title",
        ),
        migrations.AlterField(
            model_name="bid",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_bids",
                to=settings.AUTH_USER_MODEL,
                verbose_name="bidder",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="auctions.listing",
            ),
        ),
    ]
